services:

  db:
    image: mysql:8.4
    container_name: student-management-db
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  app:
    build: .
    container_name: student-management-app
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

    depends_on:
      db:
        condition: service_healthy


volumes:
  mysql_data:
